pub const list: []const Entry = @import("tables/pet");

pub fn getById(id: u32) ?Entry {
    for (list) |h| if (h.id == id) return h;
    return null;
}

pub const Level = enum(u8) {
    min = 1,
    max = list[list.len - 1].lv,
    _,

    pub fn toInt(level: Level) u8 {
        return @intFromEnum(level);
    }
};

pub const Entry = struct {
    id: u24,
    name: LangString,
    unit_id: u32,
    element: []const u32,
    egg: u32,
    race: []const u32,
    pet_stage: u32,
    is_rename: bool,
    battle_tag: []const u32,
    size: u32,
    desc: LangString,
    unit_rotation_type: u32,
    body_type: u32,
    unit_position_get: [3]f32,
    unit_rotation_get: [3]f32,
    unit_scale_get: u32,
    unit_scale: u32,
    unit_position: []const f32,
    unit_camera_position: []const f32,
    pet_icon: []const u8,
    playercard_dress_pet: []const [3]u32,
    playercard_dress_pet_1: []const [3]u32,
    pet_battle_icon: []const []const u8,
    pet_pixel_icon: []const u8,
    pet_pixel_position: [3]f32,
    kibo_box_card_icon: []const []const u8,
    kibo_card_icon: []const u8,
    kibo_card_icon_new: []const u8,
    pet_talk_icon: []const u8,
    name_sp: []const LangString,
    kibo_box_card_icon_sp: []const []const []const u8,
    kibo_card_icon_sp: []const []const u8,
    kibo_card_icon_sp_new: []const []const u8,
    kibo_multi_team_hub_card_icon: []const u8,
    kibo_multi_team_hub_card_fv: []const u8,
    kibo_multi_team_hub_card_bg: []const u8,
    pet_talk_icon_sp: []const []const u8,
    pet_icon_sp: []const []const u8,
    pet_pixel_icon_sp: []const []const u8,
    pet_pixel_position_sp: []const [3]f32,
    grade_score_sp: []const u32,
    pet_battle_icon_sp: []const []const []const u8,
    pet_special: []const u8,
    pet_special_weight: []const u8,
    grade_score: u32,
    is_catch: bool,
    catch_hp: u32,
    catch_modulus: u32,
    catch_radian_modulus: u32,
    growth_attribute: []const MapEntry(u32, u32),
    base_attribute: []const MapEntry(u32, u32),
    dna: []const [2]u32,
    is_battle: bool,
    pet_stay_type: u32,
    stay_time: u32,
    behavior_type: u32,
    signature_skill_list: []const [3]u32,
    skill_list_count: u32,
    skill_list: []const [3]u32,
    r_propertyskill_count: u32,
    r_propertyskill_list: []const [3]u32,
    f_propertyskill_list: []const MapEntry(u32, u32),
    break_skill_list: []const MapEntry(u32, u32),
    fixed_skill_list: []const MapEntry(u32, u32),
    skill_bytes_path: []const []const []const u8,
    property_id: u32,
    collision_type: u32,
    kibo_duel_tag: []const u32,
    kibo_skill_list: []const []const u32,
    b_propertyskill_list: []const MapEntry(u32, u32),
    kibo_b_propertyskill_list: []const MapEntry(u32, u32),
    kibo_f_propertyskill_list: []const MapEntry(u32, u32),
    kibo_r_propertyskill_count: u32,
    kibo_r_propertyskill_list: []const []const u32,
    aim_range: []const u32,
    cf: []const u8,
    kibo_set_time: u32,
    kibo_type: u32,
    kibo_base_attribute: []const MapEntry(u32, u32),
    feature: []const u32,
    petlong_icon: []const u8,
    puzzle_type: []const u32,
    pet_puzzle_icon: []const u8,
    species_id: u32,
    world_property: struct {
        target_length: f32 = 0.0,
        target_length2: f32 = 0.0,
    },
    move_type: []const u32,
    default_move_type: u32,
    playercard_dress: []const [3]u32,
    iconography_num: u32,
    iconography_num_suffix: []const u8,
    iconographyshow: u32,
    iconography_task_id: []const u32,
    iconography_unit_scale: u32,
    iconography_unit_position: []const f32,
    iconography_drop: []const u32,
    iconography_map_pos: []const []const u32,
    kibo_dna_list: []const u32,
    house_type: u32,
    no_shadow: []const []const u8,
    pet_daily_refresh_prob: []const MapEntry(u32, u32),
    pet_once_refresh_prob: []const MapEntry(u32, u32),
    pet_nest_prob: []const MapEntry(u32, u32),
};

const LangString = tables.LangString;
const MapEntry = tables.MapEntry;
const tables = @import("../tables.zig");
